#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-writexl
Version  : 1.4.2
Release  : 2
URL      : https://cran.r-project.org/src/contrib/writexl_1.4.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/writexl_1.4.2.tar.gz
Summary  : Export Data Frames to Excel 'xlsx' Format
Group    : Development/Tools
License  : BSD-2-Clause MPL-2.0
Requires: R-writexl-lib = %{version}-%{release}
Requires: R-writexl-license = %{version}-%{release}
BuildRequires : R-bit64
BuildRequires : R-spelling
BuildRequires : buildreq-R
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Fast and no Java or Excel required.

%package lib
Summary: lib components for the R-writexl package.
Group: Libraries
Requires: R-writexl-license = %{version}-%{release}

%description lib
lib components for the R-writexl package.


%package license
Summary: license components for the R-writexl package.
Group: Default

%description license
license components for the R-writexl package.


%prep
%setup -q -n writexl

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695174038

%install
export SOURCE_DATE_EPOCH=1695174038
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-writexl
cp %{_builddir}/writexl/inst/COPYRIGHT %{buildroot}/usr/share/package-licenses/R-writexl/ebd45039849a00b9632ed4cd210e35d61dc8547a || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/writexl/AUTHORS
/usr/lib64/R/library/writexl/COPYRIGHT
/usr/lib64/R/library/writexl/DESCRIPTION
/usr/lib64/R/library/writexl/INDEX
/usr/lib64/R/library/writexl/LICENSE
/usr/lib64/R/library/writexl/Meta/Rd.rds
/usr/lib64/R/library/writexl/Meta/features.rds
/usr/lib64/R/library/writexl/Meta/hsearch.rds
/usr/lib64/R/library/writexl/Meta/links.rds
/usr/lib64/R/library/writexl/Meta/nsInfo.rds
/usr/lib64/R/library/writexl/Meta/package.rds
/usr/lib64/R/library/writexl/NAMESPACE
/usr/lib64/R/library/writexl/NEWS
/usr/lib64/R/library/writexl/R/writexl
/usr/lib64/R/library/writexl/R/writexl.rdb
/usr/lib64/R/library/writexl/R/writexl.rdx
/usr/lib64/R/library/writexl/WORDLIST
/usr/lib64/R/library/writexl/help/AnIndex
/usr/lib64/R/library/writexl/help/aliases.rds
/usr/lib64/R/library/writexl/help/paths.rds
/usr/lib64/R/library/writexl/help/writexl.rdb
/usr/lib64/R/library/writexl/help/writexl.rdx
/usr/lib64/R/library/writexl/html/00Index.html
/usr/lib64/R/library/writexl/html/R.css
/usr/lib64/R/library/writexl/tests/spelling.R
/usr/lib64/R/library/writexl/tests/testthat.R
/usr/lib64/R/library/writexl/tests/testthat/test-performance.R
/usr/lib64/R/library/writexl/tests/testthat/test-types.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/writexl/libs/writexl.so
/usr/lib64/R/library/writexl/libs/writexl.so.avx2
/usr/lib64/R/library/writexl/libs/writexl.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-writexl/ebd45039849a00b9632ed4cd210e35d61dc8547a
