#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-writexl
Version  : 1.5.1
Release  : 8
URL      : https://cran.r-project.org/src/contrib/writexl_1.5.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/writexl_1.5.1.tar.gz
Summary  : Export Data Frames to Excel 'xlsx' Format
Group    : Development/Tools
License  : BSD-2-Clause MPL-2.0
Requires: R-writexl-lib = %{version}-%{release}
Requires: R-writexl-license = %{version}-%{release}
BuildRequires : R-bit64
BuildRequires : R-spelling
BuildRequires : buildreq-R
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-writexl package.
Group: Libraries
Requires: R-writexl-license = %{version}-%{release}

%description lib
lib components for the R-writexl package.


%package license
Summary: license components for the R-writexl package.
Group: Default

%description license
license components for the R-writexl package.


%prep
%setup -q -n writexl
pushd ..
cp -a writexl buildavx2
popd
pushd ..
cp -a writexl buildavx512
popd
pushd ..
cp -a writexl buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740105260

%install
export SOURCE_DATE_EPOCH=1740105260
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-writexl
cp %{_builddir}/writexl/inst/COPYRIGHT %{buildroot}/usr/share/package-licenses/R-writexl/ebd45039849a00b9632ed4cd210e35d61dc8547a || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/writexl/AUTHORS
/usr/lib64/R/library/writexl/COPYRIGHT
/usr/lib64/R/library/writexl/DESCRIPTION
/usr/lib64/R/library/writexl/INDEX
/usr/lib64/R/library/writexl/LICENSE
/usr/lib64/R/library/writexl/Meta/Rd.rds
/usr/lib64/R/library/writexl/Meta/features.rds
/usr/lib64/R/library/writexl/Meta/hsearch.rds
/usr/lib64/R/library/writexl/Meta/links.rds
/usr/lib64/R/library/writexl/Meta/nsInfo.rds
/usr/lib64/R/library/writexl/Meta/package.rds
/usr/lib64/R/library/writexl/NAMESPACE
/usr/lib64/R/library/writexl/NEWS
/usr/lib64/R/library/writexl/R/writexl
/usr/lib64/R/library/writexl/R/writexl.rdb
/usr/lib64/R/library/writexl/R/writexl.rdx
/usr/lib64/R/library/writexl/WORDLIST
/usr/lib64/R/library/writexl/help/AnIndex
/usr/lib64/R/library/writexl/help/aliases.rds
/usr/lib64/R/library/writexl/help/paths.rds
/usr/lib64/R/library/writexl/help/writexl.rdb
/usr/lib64/R/library/writexl/help/writexl.rdx
/usr/lib64/R/library/writexl/html/00Index.html
/usr/lib64/R/library/writexl/html/R.css
/usr/lib64/R/library/writexl/tests/spelling.R
/usr/lib64/R/library/writexl/tests/testthat.R
/usr/lib64/R/library/writexl/tests/testthat/test-performance.R
/usr/lib64/R/library/writexl/tests/testthat/test-types.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/writexl/libs/writexl.so
/V4/usr/lib64/R/library/writexl/libs/writexl.so
/VA/usr/lib64/R/library/writexl/libs/writexl.so
/usr/lib64/R/library/writexl/libs/writexl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-writexl/ebd45039849a00b9632ed4cd210e35d61dc8547a
